# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyCSTV' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyCSTV

pod 'Alamofire', '~> 5.5'
pod 'KeychainSwift', '~> 20.0'
pod 'Kingfisher', '~> 7.0'

  target 'MyCSTVTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyCSTVUITests' do
    # Pods for testing
  end

end
